FlatFinding/Models/Enquery.cs
namespace FlatFinding.Models
{
    public class Enquery
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Contact { get; set; }
        public string query { get; set; }
    }
}

FlatFinding/Models/Notice.cs
namespace FlatFinding.Models
{
    public class Notice
    {
        public int? NoticeId { get; set; }
        public string NoticeName { get; set; }
        public string Description { get; set; }
        public DateTime PublishDate { get; set; }

    }
}

FlatFinding/Controllers/FlatController.cs
using FlatFinding.Data;
using FlatFinding.Migrations;
using FlatFinding.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using FlatFinding.ViewModel;

namespace FlatFinding.Controllers
{
    [Authorize]
    public class FlatController : Controller
    {
        private readonly FlatFindingContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public FlatController(UserManager<ApplicationUser> userManager, FlatFindingContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var AllFlats = await _context.Flats
                .Where(f => f.IsBooking == 0 && f.Available == "YES" && f.FlatStatus == "Accepted").ToListAsync();
            ViewBag.Flats = AllFlats;
            ViewBag.Count = AllFlats.Count;
            return View();
        }
        
        public async Task<IActionResult> AreaWise(string id)
        {
            var AllFlats = await _context.Flats 
                .Where(f => f.IsBooking == 0 && f.Available == "YES" && f.FlatStatus == "Accepted").ToListAsync();

            AllFlats = AllFlats.Where(flat => flat.AreaName == id).ToList();

            ViewBag.Flats = AllFlats;
            ViewBag.Count = AllFlats.Count;
            return View("Index");
        }

        public async Task<IActionResult> Search(SearchViewModel model)
        {
            var AllFlats = await _context.Flats
                .Where(f => f.IsBooking == 0 && f.Available == "YES" && f.FlatStatus == "Accepted").ToListAsync();

            AllFlats = AllFlats.Where(flat => (flat.AreaName == model.Area) && (flat.Types == model.Type)).ToList();
            AllFlats = AllFlats.Where(flat => (flat.TotalCost >= (model.Price - 3000) && flat.TotalCost <= (model.Price + 2000))).ToList();
            AllFlats = AllFlats.Where(flat => (flat.RoomNo >= (model.Room - 2) && flat.RoomNo <= (model.Room + 2))).ToList();


            ViewBag.Flats = AllFlats;
            ViewBag.Count = AllFlats.Count;
            return View("Index");
        }

        public async Task<IActionResult> FlatDetails(int? id, int IsNotBooking = 0)
        {
            var FlatDetail = await _context.Flats
                .FirstOrDefaultAsync(m => m.FlatId == id);
            var comments = await _context.Comments
                .Where(f => f.FlatId == id).ToListAsync();

            if (FlatDetail == null) 
                return NotFound();
            
            

            FlatDetail.Views = FlatDetail.Views + 1;

            _context.Update(FlatDetail);
            await _context.SaveChangesAsync();

            ViewBag.FlatDetail = FlatDetail;
            ViewBag.Comments = comments;

            if(IsNotBooking == 1)
            {
                TempData["flat"] = "You can Not Booked more then 5 Flats";
            }
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(Flat model, IFormFile? file)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            model.OwnerId = userId;

            // If search on flat and check same flat entry or not
            if (ModelState.IsValid)
            {
                var flatExist = await _context.Flats.Where(
                f => f.FlatNumber == model.FlatNumber
               && f.RoadNo== model.RoadNo && f.HouseNo== model.HouseNo
               && f.sectorNo == model.sectorNo && f.AreaName== model.AreaName
               ).ToListAsync();

            if(flatExist.Count > 0)
            {
                ViewBag.SameFlat = "Same";
            }
            else
            {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    if (file != null)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        var uploads = Path.Combine(wwwRootPath, @"img");
                        var extension = Path.GetExtension(file.FileName);

                        if (model.Picture != null)
                        {
                            var oldImagePath = Path.Combine(wwwRootPath, model.Picture.TrimStart('\\'));
                            if (System.IO.File.Exists(oldImagePath))
                            {
                                System.IO.File.Delete(oldImagePath);
                            }
                        }


                        using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                        {
                            file.CopyTo(fileStreams);
                        }

                        model.Picture = @"\img\" + fileName + extension;

                    };

                    model.FlatStatus = "Pending";

                    _context.Add(model);
                    await _context.SaveChangesAsync();
                    TempData["flat"] = "Flat Save Successfully";
                    return RedirectToAction("FlatOwnerProfile", "Dashboard");
                }
            

           
               
            }
            TempData["flat"] = "Flat Not Save";
            return View( model);
        }

        [HttpGet]
        public IActionResult UpdateFlat(int id)
        {
            var model = _context.Flats.FirstOrDefault(x => x.FlatId == id);

            ViewBag.Picture = model.Picture;
            return View(model);
        }

        [HttpPost]
        public IActionResult UpdateFlat(Flat model, IFormFile? file)
        {
           
          

            var flatExist =  _context.Flats.Where(
            f => f.FlatNumber == model.FlatNumber
           && f.RoadNo == model.RoadNo && f.HouseNo == model.HouseNo
           && f.sectorNo == model.sectorNo && f.AreaName == model.AreaName
           && f.Types == model.Types && f.Phone ==  model.Phone 
           && f.Description == model.Description && f.IsBooking == 0  
           ).ToList();

            if (flatExist.Count > 0)
            {
                ViewBag.SameFlat = "Same";
            }
            else
            {
                var flat = _context.Flats.AsNoTracking().FirstOrDefault(f => f.FlatId == model.FlatId);
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"img");
                    var extension = Path.GetExtension(file.FileName);

                    if (model.Picture != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, model.Picture.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }


                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    flat.Picture = @"\img\" + fileName + extension;

                };


                model.Picture = flat.Picture;
                model.OwnerId = flat.OwnerId;

                _context.Flats.Update(model);
                _context.SaveChanges();
                return RedirectToAction("UpdateFlat", new { id = model.FlatId });
            }

           
            
            return View(model);
        }
        public async Task<IActionResult> DeleteFlat(int id)
        {
            var userModel = await _context.Flats.FindAsync(id);
            if (userModel != null)
            {
                _context.Flats.Remove(userModel);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("FlatOwnerProfile", "Dashboard");
        }


        [HttpPost]
        public async Task<IActionResult> Comment(int FlatId, string comment)
        {
            try
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                var user = await _userManager.FindByIdAsync(userId);
                Comment comt = new Comment()
                {
                    FlatId = FlatId,
                    comment = comment,
                    Date = DateTime.Now,
                    Name = user.Name,
                };

                _context.Comments.Add(comt);
                await _context.SaveChangesAsync();
            }
            catch(Exception)
            {
                
            }


            return RedirectToAction("FlatDetails", new { id = FlatId });
        }
    }
}

FlatFinding/Controllers/HomeController.cs
using FlatFinding.Data;
using FlatFinding.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace FlatFinding.Controllers
{
    public class HomeController : Controller
    {
        private readonly FlatFindingContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public HomeController(FlatFindingContext context, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager,
                                    SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var BookingFlats = await _context.FlatBookeds.ToListAsync();

            var userRole = await _roleManager.FindByNameAsync("User");
            var ownerRole = await _roleManager.FindByNameAsync("Owner");
            var AllFlats = await _context.Flats.Where(f => f.IsBooking == 0 && f.Available == "YES" && f.FlatStatus == "Accepted").ToListAsync();
            
            var Flats = AllFlats
                        .Where(f => f.IsBooking == 0 && f.Available == "YES" && f.FlatStatus == "Accepted")
                        .OrderByDescending(f => f.Views) 
                        .Take(10)
                        .ToList();
            var AreaWise = AllFlats.Where(f => f.IsBooking == 0 && f.Available == "YES" && f.FlatStatus == "Accepted")
                            .GroupBy(flat => flat.AreaName)
                            .Select(group => new
                            {
                                AreaName = group.Key,
                                FlatCount = group.Count()
                            })
                            .ToList();

            if (userRole != null && ownerRole != null)
            {
                var users = await _userManager.GetUsersInRoleAsync(userRole.Name);
                var owner = await _userManager.GetUsersInRoleAsync(ownerRole.Name);
                ViewBag.UserCount = users.Count;
                ViewBag.OwnerCount = owner.Count;
            }

            ViewBag.AllFlats = AllFlats.Count();
            ViewBag.BookedFlats = BookingFlats.Count;
            ViewBag.RecomendedFlats = Flats;
            ViewBag.AreaWise = AreaWise;


            return View();
        }

        public async Task<IActionResult> Notice()
        {
            var Notice = await _context.Notices.ToListAsync();
            ViewBag.Notice = Notice;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> suscriber(string email)
        {
            if (!string.IsNullOrEmpty(email))
            {
                var isEmail = _context.Suscribers.AsNoTracking().FirstOrDefault( f => f.email == email);
                if(isEmail == null)
                {
                    Suscriber sub = new Suscriber()
                    {
                        email = email
                    };
                    _context.Suscribers.Add(sub);
                    await _context.SaveChangesAsync();
                    TempData["subscribe"] = "Email Successfully Save";
                    return RedirectToAction("Index");
                }
                
            }

            TempData["subscribe"] = "Email Not Save";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Enquery()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Enquery(Enquery model)
        {
            if(ModelState.IsValid)
            {
                _context.Enqueries.Add(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Enquery");
            }
            else
            {
                return View(model);
            }
           
            
        }



    }
}

FlatFinding/Views/Home/Enquery.cshtml
@model FlatFinding.Models.Enquery

<div class="RecomendedArea mt-5 mb-3">


    <div class="card userBookedList mb-3 mt-3">

        <div class="card-body">
            <h5 class="mb-3">Submit your Question / Suggestion</h5>
            <form asp-controller="Home" asp-action="Enquery" method="post">
                <div class="row">
                    <div class="col-6 mb-3">
                        <label asp-for="Name" class="mb-1"> <b>Your Name</b></label>
                        <input asp-for="Name" type="text" class="form-control" />
                    </div>
               
              
                    <div class="col-6 mb-3">
                        <label asp-for="Contact" class="mb-1"> <b>Contact</b></label>
                        <input asp-for="Contact" type="text" class="form-control" />
                    </div>

              
                    <div class="col-12 mb-3">
                        <label asp-for="Subject" class="mb-1"> <b>Query Subject</b></label>
                        <input asp-for="Subject" type="text" class="form-control" />
                    </div> 
                    
                    <div class="col-12 mb-3">
                        <label asp-for="query" class="mb-1"> <b>Write your Query</b></label>
                        <textarea asp-for="query" rows="4" type="text" class="form-control" >

                        </textarea>
                    </div>

                  
                        <button type="submit" class="btn btn-primary">Send</button>
                   
                </div>
            </form>


        </div>


    </div>

</div>

FlatFinding/Views/Home/Index.cshtml
@model FlatFinding.ViewModel.SearchViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Flat Finding";
}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-blue order-card">
                <div class="card-block">
                    <h5 class="mb-2 text-center">Active User</h5>
                    <h5 class="text-center">@ViewBag.UserCount</h5>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-green order-card">
                <div class="card-block">
                    <h5 class="mb-2 text-center">Active Flat Owner</h5>
                    <h5 class="text-center">@ViewBag.OwnerCount</h5>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-yellow order-card">
                <div class="card-block">
                    <h5 class="mb-2 text-center">Available Flats</h5>
                    <h5 class="text-center">@ViewBag.AllFlats </h5>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h5 class="mb-2 text-center">Completed Booking</h5>
                    <h5 class="text-center"> @ViewBag.BookedFlats</h5>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="mb-3">
    <div class="d-flex container HeaderBanar">
        <div class="HomeHeaderLef">
            @*TODO:
            1) Advance Search: (Area, price, room, type(family, bacelor, sublate) )
            2) Recomend by your profile or behavior, Area ML
            3) Notice for your and Comment section 
            *@
            <div class="card SearchGrdint">
                <div class="card-body">
                    <h5 style="text-align: center;">Find the Right Flat</h5>

                    <h5>Search </h5>
                  
                    <form class="p-2" asp-controller="Flat" asp-action="Search" method="post">

                        @*<div class="text-center">
                        <input type="radio" /> <b style="margin-right: 30px">AI Recomanded Search</b>
                        <input type="radio" /> <b>General Search</b>
                        </div>*@

                        <div class="row  mt-3">
                            <div class="col-6 mb-3">
                                <label asp-for="Area" class="mb-1"><b> Select Area</b></label>
                                <select asp-for="Area" class="form-control">
                                <option value="Airport">Airport</option>
                                <option value="Uttara"> Uttara</option>
                                <option value="Mirpur"> Mirpur</option>
                                <option value="Bonani"> Bonani</option>
                                <option value="Gulsan"> Gulsan</option>
                                <option value="Dhanmondi"> Dhanmondi</option>
                                <option value="Motijil"> Motijil</option>
                        </select>
                            </div>

                            <div class="col-6 mb-3">
                                <label asp-for="Price" class="mb-1"> <b>Price Range -2000 to +2000 </b></label>
                                <input asp-for="Price" type="number" class="form-control" />
                            </div>

                            <div class="col-6 mb-3">
                                <label asp-for="Room" class="mb-1"> <b>Number of Rooms </b></label>
                                <select asp-for="Room" class="form-control">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                </select>
                            </div>
                            <div class="col-6 mb-3">
                                <label asp-for="Type" class="mb-1"><b>Type of Flat </b></label>
                                <select asp-for="Type" class="form-control">
                                    <option value="Family">Family</option>
                                    <option value="Bachelor">Bachelor</option>
                                    <option value="Sublate">Sublate</option>

                                </select>
                            </div>



                        </div>
                        <button class="btn btn-success mt-3 mb-3" >Search Now</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="HomeHeaderRight">
            <div class="card SideBarGrdint2">
                <div class="card-header text-center">See Area wise</div>
                <div class="card-body d-flex flex-wrap">

                    @foreach (var flat in ViewBag.AreaWise)
                     {
                        <a class="btn btn-outline-success mb-2" style="margin-right: 4px" asp-area="" asp-controller="Flat" asp-action="AreaWise" asp-route-id="@flat.AreaName"> @flat.AreaName (@flat.FlatCount)</a>
                     }
                   
                   @* <a class="btn btn-outline-success mb-2" style="margin-right: 4px" asp-area="" asp-controller="Home" asp-action="Index">Airport (7)</a>
                    <a class="btn btn-outline-success mb-2" style="margin-right: 4px" asp-area="" asp-controller="Home" asp-action="Index">Mirpur (15)</a>
                    <a class="btn btn-outline-success mb-2" style="margin-right: 4px" asp-area="" asp-controller="Home" asp-action="Index">Motijil (9)</a>
                    <a class="btn btn-outline-success mb-2" style="margin-right: 4px" asp-area="" asp-controller="Home" asp-action="Index">Basundhara (11)</a>*@

                </div>
               @* <div class="p-2">
                    <p>Quick Update</p>
                    New Flat (24h) <br />
                    Last 7 days
                </div>*@

                <div class="p-1">
                      <hr />
                    <p class="text-center" > <small> Best Flat with Best Match </small></p>
                </div>
            </div>
        </div>
    </div>
    <div class="RecomendedArea mt-5 mb-3">
        <h5 class="mx-5">Recomanded Flat</h5>
        <div class="d-flex flex-wrap justify-content-center">
            @foreach(var item in ViewBag.RecomendedFlats)
            {
                <div class="card mt-3 mb-3 " style="width: 300px; height:340px; margin-right: 20px;">
                    <img class="card-img-top" style="overflow: hidden" src="@item.Picture" alt="Card image cap">
                    <div class="card-body">
                       <div>
                            <small class="dec_flat"><b>Flat Name:</b> @item.Name</small> <br />
                            <small class="dec_flat"><b>Address:</b> H: @item.HouseNo, R: @item.RoadNo, Sc: @item.sectorNo, @item.AreaName </small> <br />
                            <small class="dec_flat "><b> Price:</b> @item.TotalCost tk/month </small>
                            <small class="dec_flat mx-3"><b>  Type:</b>@item.Types</small> <br />
                            <small class="dec_flat"><b> Rooms:</b>@item.RoomNo</small>
                       </div>
                       <div>
                            <b>Views</b> @item.Views
                            <a class="btn btn-primary" style="margin-left: 70px" asp-controller="Flat" asp-action="FlatDetails" asp-route-id="@item.FlatId">Booked Now</a>
                       </div>
                    </div>
                </div>
            }
        </div>

    </div>

    <div class="RecomendedArea">
        <div class="card" style="background: #e1e1e1;">
            <div class="card-body">
               
    @if (TempData["subscribe"] != null)
    {
            <script type="text/javascript" >
                window.onload = function () {
                    Swal.fire(
                        '',
                       '@TempData["subscribe"]',
                       ''
                    )
                };
             </script>
    }
   
       
                  <form asp-controller="home" asp-action="suscriber" method="post">
                      <div class="row">
                        <div class="col-4"></div>
                        <div class="col-4 mb-3">
                            <label for="email" class="mb-1"> <b>Subscribe with your Email</b></label>
                            <input for="email" name="email" type="email" class="form-control" autocomplete="off" />
                           
                        </div>
                        <div class="col-2 mt-4">
                            <button type="submit" class="btn btn-primary">Subscribe</button>
                        </div>
                      </div>
                </form>
            </div>
        </div>
      
    </div>
</div>


   

FlatFinding/Views/Home/Notice.cshtml
<div class="RecomendedArea mt-5 mb-3">


    <div class="card userBookedList mb-3 mt-3">

        <div class="card-body">
            <h5 class="mb-3">See All Notice</h5>
            <div class="row">
                @foreach (var nt in ViewBag.Notice)
                {
                    <div class="col-sm-6">
                        <div class="card border-success">
                            <div class="card-body">
                                <h6 class="card-title">@nt.NoticeName</h6>
                                <p> <small>@nt.PublishDate</small></p>
                                <p class="card-text">@nt.Description</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
          
           
        </div>


    </div>

</div>